# Generated by Django 5.0.6 on 2025-04-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_flows', models.IntegerField(default=0)),
                ('benign_flows', models.IntegerField(default=0)),
                ('attack_flows', models.IntegerField(default=0)),
                ('attack_percentage', models.FloatField(default=0.0)),
                ('attack_types', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
