name: Build and Push to DockerHub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: ./ntad
        file: ./ntad/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/network-traffic-anomaly-api:latest
